name: Bug Report
description: File a bug report.
title: "[Bug] "
labels: ["bug", "triage"]
assignees:
  - Gueztt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info (optional)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue faced.
      description:  You can upload log files here. Also tell us, what did you expect to happen?
      placeholder: Tell us what you see or don`t see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: "1.0.0"
    validations:
      required: true
      
  - type: input
    id: windows_version
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? You can copy version from within the app setings.
      placeholder: "10.0.22624.1465"
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. You can see the latest log file in App Settings> Open Logs Location.
      render: shell
